api/urls.py
from unicodedata import name
from django.urls import path, include
from api import views 

urlpatterns = [
    path("get-gri-data/",views.grievance_display,name="get-gri-data"),
    path("upload-gri/",views.create_gri,name="upload-data"),

    path("upvote-gri/",views.upvote_grievance,name="upvote-gri"),
    path("get-severity/",views.get_severity,name="get-severity") #temprary delete later

]

dashboard/urls.py
from django.urls import path, include
from dashboard import views

app_name="dashboard"
urlpatterns = [

    path('signin/', views.signin, name="signin"),
    path('register/', views.register, name="register"),
    path('acsetting/', views.accountSetting, name="acsetting"),
    path('signout/',views.signout, name="signout"),

    path('',views.muncipalDashboard,name="muncipal_dashboard"),
    path('workspace/',views.workSpace, name="workspace"),

    path('grievance-detail/<int:gri_id>/',views.grievance, name="grievance-detail"),

    #JSON Response AJAX
    path('display-modal-folder-list/',views.display_Modal_Folder_list),
    
    #used in two way for workspace nad for modal
    path('display-desks-list/',views.displayDeskList,name="display-desks-list"),
    path('workspace-inside-desk/',views.workspace_inside_desk,name="workspace-inside-desk"),
    path('workspace-inside-folder/',views.workspace_inside_folder,name="workspace-inside-folder"),

    path('display-workspace-desk-folders/',views.display_WorkSpace_DeskFolders,name="display-desk-folders"),

    #move gri to folder in MoveGri.js file
    path('move-gri-to-folder/',views.move_gri_to_folder,name="move-gri-to-folder"),
    path('move-gri-to-desk/',views.move_gri_to_desk,name="move-gri-to-desk"),

    path('reject-gri/',views.reject_gri,name="move-gri-to-desk"),

    path('create-desk/',views.createDesk,name="create-desk"),
    path('create-folder/',views.createFolder,name="create-desk"),
    
    path('filter-data/', views.filter_data, name="filter_data"),
]

project_clean/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('gri/', include('grievance_data.urls')),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grievance_data/models.py
from ast import arg
from django.db import models
from django.dispatch import receiver
from authapp.models import CitizenProfile, User, MCProfile, Location
from django.db.models.signals import post_save, pre_save
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files import File
from ml_models.ml_functions import gri_priority, gri_severity   

from cloudinary.models import CloudinaryField

CAT_NAME = (
    ("Garbage","Garbage"),
    ("POTHOLE","POTHOLE"),
    ("Fallen Tree","Fallen Tree")
)


class Category(models.Model):
    cat_name = models.CharField(max_length=250,choices=CAT_NAME)
    cat_value = models.IntegerField(default=0)
    def __str__(self):
        return self.cat_name

class Grievance(models.Model):
    gri_img = CloudinaryField('image', transformation={'width': '450', 'height': '600', 'crop':'scale','quality':'80'}, folder='/media/grievance_pics', format="jpeg",)
    #gri_img = models.ImageField(upload_to="grievance_pics")

    gri_title = models.CharField(max_length=250)
    gri_desc = models.TextField(null=True)
    gri_category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True, related_name='category')
    gri_upvote = models.PositiveIntegerField(default=0)
    gri_upvote_list = models.ManyToManyField(CitizenProfile,blank=True)
    #gri_upvote = models.IntegerField(default=0)
    gri_severity = models.IntegerField(default=0)
    gri_priority = models.IntegerField(default=0)
    gri_uploaded_user = models.ForeignKey(CitizenProfile,on_delete=models.CASCADE, related_name='uploaded_user')
    gri_location = models.OneToOneField(Location,on_delete=models.CASCADE,null=True)
    gri_timeStamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.gri_title

    def save(self,*args, **kwargs):
        if not self._state.adding:
            self.gri_priority = gri_priority(self)      
        super().save(*args,**kwargs)

# def reduce_image_size(profile_pic):
#     print(profile_pic)
#     img = Image.open(profile_pic)
#     thumb_io = BytesIO()
#     img.thumbnail((500,668))
#     img.save(thumb_io, "jpeg", quality=50)
#     new_image = File(thumb_io, name=profile_pic.name)
#     return new_image

# @receiver(pre_save,sender=Grievance,)
# def pre_save_grievacne(sender, instance, **kwargs):
#     img = Image.open(instance.gri_img)
#     thumb_io = BytesIO()
#     img.thumbnail((500,668))
#     img.save(thumb_io, "jpeg", quality=50)
#     instance.gri_img = File(thumb_io, name=instance.gri_img.name)

@receiver(post_save,sender=Grievance,)
def post_save_grievacne(sender, instance, **kwargs):
    if kwargs['created']:
        status = Status(status_name="Register",status_grievance=instance,status_issuedByMC=None)
        status.save()
        status = Status(status_name="Pending",status_grievance=instance,status_active=True,status_issuedByMC=None)
        status.save()

STATUS_NAME = (
    ("Register","Register"),
    ("Pending","Pending"),
    ("In Progress","In Progress"),
    ("Complete","Complete"),
    ("Rejected","Rejected")
)

class Status(models.Model):
    status_name = models.CharField(max_length=250,choices=STATUS_NAME)
    status_grievance = models.ForeignKey(Grievance,on_delete=models.CASCADE)
    status_active = models.BooleanField(default=False)
    status_timeStamp = models.DateTimeField(auto_now=True)
    status_issuedByMC = models.ForeignKey(MCProfile,on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return f"{self.status_grievance} - {self.status_name}"



# Create your models here.

templates/ajax/grievance-list.html
{% load static %}
{% for gri in grievance_list %}
<div class="col-12">
  <div class="card">
    <div class="row row-0">
      <div class="col-3">
        <img src="{{gri.gri_img.url}}" class="w-100 h-100 object-cover" alt="Card side image" />
      </div>
      <div class="col">
        <div class="card-body flex-column-reverse flex-row align-items-end h-100">
          <div class="d-flex">
            {% for status in gri.status_set.all%}
            {% if status.status_active%}
            <h1 class="" style="margin-right: auto;"><a href="{% url 'dashboard:grievance-detail' gri.id %}">{{ gri.gri_title}}</a></h1>

            {% if status.status_name == "Pending" %}
            {% else %}
            <div class="d-flex align-items-center mb-3 bg-blue-lt mx-auto py-1 px-1 rounded-2">

              <span class="avatar me-3 rounded"
                style="background-image: url({{ status.status_issuedByMC.mc_profile_img.url }})"></span>
              <div>
                <div> {{ status.status_issuedByMC.mc_user.first_name }}
                  {{ status.status_issuedByMC.mc_user.last_name }}</div>
                <div class="text-muted">{{ status.status_timeStamp|date:'d M Y'}}</div>
              </div>
            </div>
            {% endif %}
                {% if status.status_name == "In Progress" %}
                <div><span class="badge bg-primary">{{status.status_name}}</span></div>
                {% elif status.status_name == "Complete" %}
                <div><span class="badge bg-success">{{status.status_name}}</span></div>
                {% elif status.status_name == "Rejected" %}
                <div><span class="badge bg-danger">{{status.status_name}}</span></div>
                {% elif status.status_name == "Pending" %}
                <div><span class="badge bg-yellow">{{status.status_name}}</span></div>
                {% endif%}
              {% endif %}
            {% endfor %}
          </div>

          <h3>
            <span>
              <!-- Download SVG icon from http://tabler-icons.io/i/map-pin -->
              <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <circle cx="12" cy="11" r="3" />
                <path d="M17.657 16.657l-4.243 4.243a2 2 0 0 1 -2.827 0l-4.244 -4.243a8 8 0 1 1 11.314 0z" />
              </svg>
            </span>
            {{ gri.gri_location }}
          </h3>
          <div>
            <p>
              {{gri.gri_desc}}
            </p>
          </div>
          <div class="row row-card">
            <div class="col-md-6 col-xl-4">
              <div class="card card-sm">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      {% if gri.gri_category.cat_name == "Garbage" %}
                      <span class="bg-green-lt avatar">
                        <!-- Download SVG icon from http://tabler-icons.io/i/currency-dollar -->
                        <!-- Download SVG icon from http://tabler-icons.io/i/trash -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                          stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                          stroke-linejoin="round">
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <line x1="4" y1="7" x2="20" y2="7" />
                          <line x1="10" y1="11" x2="10" y2="17" />
                          <line x1="14" y1="11" x2="14" y2="17" />
                          <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                          <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                        </svg>
                      </span>
                      {% elif gri.gri_category.cat_name == "POTHOLE" %}
                      <span class="bg-blue-lt avatar">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          class="icon icon-tabler icon-tabler-atom-2"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          stroke-width="2"
                          stroke="currentColor"
                          fill="none"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        >
                          <path
                            stroke="none"
                            d="M0 0h24v24H0z"
                            fill="none"
                          ></path>
                          <circle cx="12" cy="12" r="3"></circle>
                          <line x1="12" y1="21" x2="12" y2="21.01"></line>
                          <line x1="3" y1="9" x2="3" y2="9.01"></line>
                          <line x1="21" y1="9" x2="21" y2="9.01"></line>
                          <path d="M8 20.1a9 9 0 0 1 -5 -7.1"></path>
                          <path d="M16 20.1a9 9 0 0 0 5 -7.1"></path>
                          <path d="M6.2 5a9 9 0 0 1 11.4 0"></path>
                        </svg>
                      </span>
                      {% endif %}
                    </div>
                    <div class="col">
                      <div class="font-weight-medium">{{gri.gri_category}}</div>
                      <div class="text-muted">{{ gri.gri_timeStamp|date:'d-b-Y' }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-xl-8">
              <div class="d-flex justify-content-end p-3">
                <div class="flex-column align-item-cenyer" style="margin-right: 15%">
                  <span>Score</span>
                  <h1 class="display-4">#{{gri.gri_priority}}</h1>
                </div>
                <div class="flex-column">
                  <span>Upvote</span>
                  <h1 class="display-4">{{gri.gri_upvote}}</h1>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex mt-3">
            <div class="d-flex align-items-center" style="margin-right: auto">
              <span class="avatar me-3 rounded"
                style="background-image: url({{ gri.gri_uploaded_user.citi_profile_img.url }})"></span>
              <div>
                <div>{{ gri.gri_uploaded_user.citi_user.first_name }} {{ gri.gri_uploaded_user.citi_user.last_name }}
                </div>
                <div class="text-muted">{{gri.gri_timeStamp|date:'d-b-Y H:i'}}</div>
              </div>
            </div>
            <div class="m-3">
              <a href="#" id="grievancesREJECTID_{{gri.id}}" class="btn btn-outline-danger grievance_lists_class_IDS"
                style="padding-right: 10px" data-bs-toggle="modal" data-bs-target="#modal-reject-grievances">
                Reject
                <!-- Download SVG icon from http://tabler-icons.io/i/x -->
                <svg xmlns="http://www.w3.org/2000/svg" style="margin-left: 10px; margin-right: 0" class="icon"
                  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                  stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </a>
              {% for status in gri.status_set.all%}
                {% if status.status_active%}
                  {% if status.status_name == "Pending" %}
                    <a href="#" id="grievancesID_{{gri.id}}" class="btn btn-primary grievance_lists_class_IDS" style="padding-right: 10px" data-bs-toggle="modal"
                      data-bs-target="#modal-team">
                      Move to Desk 
                      <!-- Download SVG icon from http://tabler-icons.io/i/arrow-right -->
                      <svg xmlns="http://www.w3.org/2000/svg" style="margin-left: 10px; margin-right: 0" class="icon"
                        width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                        stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <line x1="5" y1="12" x2="19" y2="12" />
                        <line x1="13" y1="18" x2="19" y2="12" />
                        <line x1="13" y1="6" x2="19" y2="12" />
                      </svg>
                    </a>
                  {% else %}
                    <a href={% url 'dashboard:grievance-detail' gri.id %} id="grievancesID_{{gri.id}}" class="btn btn-primary"  >
                      See Details
                    </a>
                  {% endif %}
                {% endif %}
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
    {% for status in gri.status_set.all%}
    {% if status.status_active%}
    {% if status.status_name == "In Progress" %}
    <div class="card-status-end bg-primary"></div>
    {% elif status.status_name == "Complete" %}
    <div class="card-status-end bg-success"></div>
    {% elif status.status_name == "Rejected" %}
    <div class="card-status-end bg-danger"></div>
    {% elif status.status_name == "Pending" %}
    <div class="card-status-end bg-yellow"></div>
    {% endif%}
    {% endif %}
    {% endfor %}

  </div>
</div>
{% endfor %}
<script>
  var selectedGrievanceID;
  $("a.grievance_lists_class_IDS").click(function () {
    selectedGrievanceID = $(this).attr("id");
    console.log(selectedGrievanceID)
  });
</script>