api/urls.py
from unicodedata import name
from django.urls import path, include
from api import views 

urlpatterns = [
    path("get-gri-data/",views.grievance_display,name="get-gri-data"),
    path("upload-gri/",views.create_gri,name="upload-data"),

    path("upvote-gri/",views.upvote_grievance,name="upvote-gri"),
    path("get-severity/",views.get_severity,name="get-severity") #temprary delete later

]

project_clean/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('gri/', include('grievance_data.urls')),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from statistics import mode
from django.db import models
from authapp.models import User,MCProfile
from grievance_data.models import Grievance

class Desk(models.Model):
    desk_name = models.CharField(max_length=250)
    desk_mc_user = models.ForeignKey(MCProfile,on_delete=models.CASCADE)
    desk_gri_files = models.ManyToManyField(Grievance,blank=True)

    def __str__(self) -> str:
        return self.desk_name


class Folders(models.Model):
    folder_desks = models.ForeignKey(Desk,on_delete=models.CASCADE,blank=True,default="")
    folder_name = models.CharField(max_length=250)
    folder_gri_file = models.ManyToManyField(Grievance,blank=True)

    def __str__(self) -> str:
        return self.folder_name

class Logs(models.Model):
    log_detailDesc = models.TextField(null=True)
    log_timeStamp = models.DateTimeField(auto_now=True)



# Create your models here.

grievance_data/models.py
from ast import arg
from django.db import models
from django.dispatch import receiver
from authapp.models import CitizenProfile, User, MCProfile, Location
from django.db.models.signals import post_save, pre_save
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files import File
from ml_models.ml_functions import gri_priority, gri_severity   

from cloudinary.models import CloudinaryField

CAT_NAME = (
    ("Garbage","Garbage"),
    ("POTHOLE","POTHOLE"),
    ("Fallen Tree","Fallen Tree")
)


class Category(models.Model):
    cat_name = models.CharField(max_length=250,choices=CAT_NAME)
    cat_value = models.IntegerField(default=0)
    def __str__(self):
        return self.cat_name

class Grievance(models.Model):
    gri_img = CloudinaryField('image', transformation={'width': '450', 'height': '600', 'crop':'scale','quality':'80'}, folder='/media/grievance_pics', format="jpeg",)
    #gri_img = models.ImageField(upload_to="grievance_pics")

    gri_title = models.CharField(max_length=250)
    gri_desc = models.TextField(null=True)
    gri_category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True, related_name='category')
    gri_upvote = models.PositiveIntegerField(default=0)
    gri_upvote_list = models.ManyToManyField(CitizenProfile,blank=True)
    #gri_upvote = models.IntegerField(default=0)
    gri_severity = models.IntegerField(default=0)
    gri_priority = models.IntegerField(default=0)
    gri_uploaded_user = models.ForeignKey(CitizenProfile,on_delete=models.CASCADE, related_name='uploaded_user')
    gri_location = models.OneToOneField(Location,on_delete=models.CASCADE,null=True)
    gri_timeStamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.gri_title

    def save(self,*args, **kwargs):
        if not self._state.adding:
            self.gri_priority = gri_priority(self)      
        super().save(*args,**kwargs)

# def reduce_image_size(profile_pic):
#     print(profile_pic)
#     img = Image.open(profile_pic)
#     thumb_io = BytesIO()
#     img.thumbnail((500,668))
#     img.save(thumb_io, "jpeg", quality=50)
#     new_image = File(thumb_io, name=profile_pic.name)
#     return new_image

# @receiver(pre_save,sender=Grievance,)
# def pre_save_grievacne(sender, instance, **kwargs):
#     img = Image.open(instance.gri_img)
#     thumb_io = BytesIO()
#     img.thumbnail((500,668))
#     img.save(thumb_io, "jpeg", quality=50)
#     instance.gri_img = File(thumb_io, name=instance.gri_img.name)

@receiver(post_save,sender=Grievance,)
def post_save_grievacne(sender, instance, **kwargs):
    if kwargs['created']:
        status = Status(status_name="Register",status_grievance=instance,status_issuedByMC=None)
        status.save()
        status = Status(status_name="Pending",status_grievance=instance,status_active=True,status_issuedByMC=None)
        status.save()

STATUS_NAME = (
    ("Register","Register"),
    ("Pending","Pending"),
    ("In Progress","In Progress"),
    ("Complete","Complete"),
    ("Rejected","Rejected")
)

class Status(models.Model):
    status_name = models.CharField(max_length=250,choices=STATUS_NAME)
    status_grievance = models.ForeignKey(Grievance,on_delete=models.CASCADE)
    status_active = models.BooleanField(default=False)
    status_timeStamp = models.DateTimeField(auto_now=True)
    status_issuedByMC = models.ForeignKey(MCProfile,on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return f"{self.status_grievance} - {self.status_name}"



# Create your models here.

templates/Base HTML/ModalDeskTemplate.html
{% load static %}
{% for desk in desk_list %}
<div class="col-auto">
  <a
    href="#"
    id="modalDeskID_{{desk.id}}"
    class="avatar avatar-upload rounded modal_desk_icon"
    data-bs-toggle="modal"
    data-bs-target="#modal-select-folder"
  >
    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
    <svg
      xmlns="http://www.w3.org/2000/svg"
      x="0px"
      y="0px"
      width="24"
      height="24"
      viewBox="0 0 172 172"
      style="fill: #000000"
    >
      <g
        fill="none"
        fill-rule="nonzero"
        stroke="none"
        stroke-width="1"
        stroke-linecap="butt"
        stroke-linejoin="miter"
        stroke-miterlimit="10"
        stroke-dasharray=""
        stroke-dashoffset="0"
        font-family="none"
        font-weight="none"
        font-size="none"
        text-anchor="none"
        style="mix-blend-mode: normal"
      >
        <path d="M0,172v-172h172v172z" fill="none"></path>
        <g fill="#3498db">
          <path
            d="M3.44,27.52v3.44v20.64h6.88v92.88h20.64v-92.88h68.8v79.12v3.44v10.32h6.88v-10.32h48.16v10.32h6.88v-10.32v-3.44v-79.12h6.88v-24.08zM10.32,34.4h151.36v10.32h-2.86219c-0.37149,-0.0614 -0.75054,-0.0614 -1.12203,0h-53.91797c-0.37149,-0.0614 -0.75054,-0.0614 -1.12203,0h-74.55797c-0.37149,-0.0614 -0.75054,-0.0614 -1.12203,0h-12.63797c-0.37149,-0.0614 -0.75054,-0.0614 -1.12203,0h-2.89578zM17.2,51.6h6.88v86h-6.88zM106.64,51.6h48.16v20.64h-48.16zM130.72,58.48c-1.89986,0 -3.44,1.54014 -3.44,3.44c0,1.89986 1.54014,3.44 3.44,3.44c1.89986,0 3.44,-1.54014 3.44,-3.44c0,-1.89986 -1.54014,-3.44 -3.44,-3.44zM106.64,79.12h48.16v20.64h-48.16zM130.72,86c-1.89986,0 -3.44,1.54014 -3.44,3.44c0,1.89986 1.54014,3.44 3.44,3.44c1.89986,0 3.44,-1.54014 3.44,-3.44c0,-1.89986 -1.54014,-3.44 -3.44,-3.44zM106.64,106.64h48.16v20.64h-48.16zM130.72,113.52c-1.89986,0 -3.44,1.54014 -3.44,3.44c0,1.89986 1.54014,3.44 3.44,3.44c1.89986,0 3.44,-1.54014 3.44,-3.44c0,-1.89986 -1.54014,-3.44 -3.44,-3.44z"
          ></path>
        </g>
      </g>
    </g>
  </svg>
  <span class="avatar-upload-text">{{ desk.desk_name }}</span>
  </a>
</div>
{% endfor %}

<div class="col-auto">
  <a href="#" class="avatar avatar-upload rounded" id="add-desk-button" data-bs-toggle="modal"
    data-bs-target="#modal-add-desk">
    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
      stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <line x1="12" y1="5" x2="12" y2="19"></line>
      <line x1="5" y1="12" x2="19" y2="12"></line>
    </svg>
    <span class="avatar-upload-text">Add</span>
  </a>
</div>
<script src="{% static 'js/DisplayFolderModal.js' %}"></script>

templates/Base HTML/messages.html
{% if messages %}
                {% for message in messages  %}

                

                <div class="alert alert-important {{message.tags}}  alert-dismissible my-4 mx-3" role="alert"style="position:fixed;bottom:0;right:0;z-index:99999999" >
                    <div class="d-flex">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon alert-icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><circle cx="12" cy="12" r="9"></circle><line x1="12" y1="8" x2="12.01" y2="8"></line><polyline points="11 12 12 12 12 16 13 16"></polyline></svg>
                        </div>
                        <div>
                            {{ message }}
                        </div>
                    </div>
                    <a class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="close"></a>
                </div>
                {% endfor %}
                {% endif %}

templates/Base HTML/modalFolderTemplate.html
{% load static %}
<div class="modal-header">
  <h5 class="modal-title">Select Folder</h5>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="modal"
    aria-label="Close"
  ></button>
</div>
<div class="modal-body">
  <div class="row mb-3 align-items-end">
    <!-- AJAX Part select folder -->
    <div class="col-auto">
      {% for folder in desk_single.folders_set.all%}
      <a
        href="#"
        id="folder-modal-id_{{folder.id}}"
        class="avatar avatar-upload rounded folder-modal-list"
      >
        <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
        <img
          src="https://img.icons8.com/external-kmg-design-flat-kmg-design/32/000000/external-folder-ui-essential-kmg-design-flat-kmg-design.png"
        />
        <span class="avatar-upload-text">{{folder.folder_name}}</span>
      </a>
      {% endfor %}
    </div>

    <div class="col-auto">
      <a
        href="#"
        id="folder-modal-deskID_{{desk_single.id}}"
        class="avatar avatar-upload rounded folder-modal-add-button"
        data-bs-toggle="modal"
        data-bs-target="#modal-add-folder"
      >
        <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="icon"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          stroke-width="2"
          stroke="currentColor"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <line x1="12" y1="5" x2="12" y2="19"></line>
          <line x1="5" y1="12" x2="19" y2="12"></line>
        </svg>
        <span class="avatar-upload-text">Add</span>
      </a>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Grievances</h3>
  </div>
  <div
    class="list-group list-group-flush overflow-auto"
    style="max-height: 35rem"
  >
    {% for gri in desk_single.desk_gri_files.all %} 
      {% for status in gri.status_set.all%} 
        {% if status.status_active%} 
          {% if status.status_name == "In Progress" %}
            <div class="list-group-item bg-blue-lt">
          {% elif status.status_name == "Complete" %}
            <div class="list-group-item bg-green-lt">
          {% elif status.status_name == "Rejected" %}
            <div class="list-group-item bg-red-lt">
          {% elif status.status_name == "Pending" %}
            <div class="list-group-item bg-yellow-lt">
          {% endif%} 
        {% endif %} 
      {% endfor %}

            <div class="row">
              <div class="col-auto">
                <a href="#">
                  <span class="avatar">
                    {% if gri.gri_category.cat_name == "Garbage" %}
                    <span class="bg-green-lt avatar">
                      <!-- Download SVG icon from http://tabler-icons.io/i/currency-dollar -->
                      <!-- Download SVG icon from http://tabler-icons.io/i/trash -->
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="icon"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        stroke-width="2"
                        stroke="currentColor"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <line x1="4" y1="7" x2="20" y2="7" />
                        <line x1="10" y1="11" x2="10" y2="17" />
                        <line x1="14" y1="11" x2="14" y2="17" />
                        <path
                          d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"
                        />
                        <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                      </svg>
                    </span>
                    {% elif gri.gri_category.cat_name == "POTHOLE" %}
                    <span class="bg-blue-lt avatar">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="icon icon-tabler icon-tabler-atom-2"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        stroke-width="2"
                        stroke="currentColor"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path
                          stroke="none"
                          d="M0 0h24v24H0z"
                          fill="none"
                        ></path>
                        <circle cx="12" cy="12" r="3"></circle>
                        <line x1="12" y1="21" x2="12" y2="21.01"></line>
                        <line x1="3" y1="9" x2="3" y2="9.01"></line>
                        <line x1="21" y1="9" x2="21" y2="9.01"></line>
                        <path d="M8 20.1a9 9 0 0 1 -5 -7.1"></path>
                        <path d="M16 20.1a9 9 0 0 0 5 -7.1"></path>
                        <path d="M6.2 5a9 9 0 0 1 11.4 0"></path>
                      </svg>
                    </span>
                    {% endif %}
                  </span>
                </a>
                
              </div>
              <div class="col text-truncate">
                <div class="d-flex">
                  <a href="#" class="text-body d-block" style="margin-right: auto;">{{ gri.gri_title }}</a>
                    {% for status in gri.status_set.all%}
                      {% if status.status_active%}
                        {% if status.status_name == "In Progress" %}
                        <div><span class="badge bg-primary">{{status.status_name}}</span></div>
                        {% elif status.status_name == "Complete" %}
                        <div><span class="badge bg-success">{{status.status_name}}</span></div>
                        {% elif status.status_name == "Rejected" %}
                        <div><span class="badge bg-danger">{{status.status_name}}</span></div>
                        {% elif status.status_name == "Pending" %}
                        <div><span class="badge bg-yellow">{{status.status_name}}</span></div>
                        {% endif%}
                      {% endif %}
                    {% endfor %}
                  </div>
                <div class="text-muted text-truncate mt-n1">{{ gri.gri_location }}</div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-link link-secondary" data-bs-dismiss="modal">
          Cancel
        </a>
        <a href="#" id="move-to-desk-button" class="btn btn-primary ms-auto" data-bs-dismiss="modal">
          <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
          Move Here
          <svg
            xmlns="http://www.w3.org/2000/svg"
            style="margin-left: 10px; margin-right: 0"
            class="icon"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <line x1="5" y1="12" x2="19" y2="12" />
            <line x1="13" y1="18" x2="19" y2="12" />
            <line x1="13" y1="6" x2="19" y2="12" />
          </svg>
        </a>
      </div>
      <script src="{% static 'js/MoveGrievance.js' %}"></script>
    {% comment %} </div>
  </div>
</div> {% endcomment %}